### ISSUE TITLE
Receive error attempting to connect to google: loopback flow has been blocked...

### ISSUE THREAD

**Issue by Spokey42** [prrvchr/OAuth2OOo#10]
Not sure what other information you would like but it is libre office 7.3.  Installed jave jre, this, and the gContactOOo.  

Error 400: invalid_request
The loopback flow has been blocked in order to keep users secure. Follow the Loopback IP Address flow migration guide linked in the developer docs below to migrate your app to an alternative method.
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/loopback-migration)

**Comment by Spokey42** [comment]
I backed up as when I went through the documentation I realized that I had not installed the jdbc extension.  I had a problem there, so I uninstalled everything.  Rebooted.  Installed java.  As the first extension, I tried the jdbc.  I get the error below during installation.  As best I can tell I do have the most recent jre.  

![image](https://user-images.githubusercontent.com/49701103/204113156-2d87bc45-c3bb-4901-9364-85f80bbf10cc.png)



(com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.UnsupportedClassVersionError: io/github/prrvchr/jdbcdriver/RegistrationHandler has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0\X000ajava stack trace:\X000ajava.lang.UnsupportedClassVersionError: io/github/prrvchr/jdbcdriver/RegistrationHandler has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0\X000d\X000a\X0009at java.lang.ClassLoader.defineClass1(Native Method)\X000d\X000a\X0009at java.lang.ClassLoader.defineClass(Unknown Source)\X000d\X000a\X0009at java.security.SecureClassLoader.defineClass(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader.defineClass(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader.access$100(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader$1.run(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader$1.run(Unknown Source)\X000d\X000a\X0009at java.security.AccessController.doPrivileged(Native Method)\X000d\X000a\X0009at java.net.URLClassLoader.findClass(Unknown Source)\X000d\X000a\X0009at java.lang.ClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at java.lang.ClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at java.net.FactoryURLClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at java.lang.ClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:53)\X000d\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:376)\X000d\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

**Comment by Spokey42** [comment]
Started all over.  Installed the jre from your link.  JDBC installed OK now.  But I still get that original error trying to connect.  2FA is off for that account so that is not an issue.

**Comment by prrvchr** [comment]
Hi [Spokey42](https://github.com/Spokey42),

Java must be at least version **11**.

for the error:
```
Error 400: invalid_request
The loopback flow has been blocked in order to keep users secure. Follow the Loopback IP Address flow migration guide linked in the developer docs below to migrate your app to an alternative method.
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/loopback-migration)
```
We must now use [OAuth2OOo version **0.0.6**](https://github.com/prrvchr/OAuth2OOo/blob/master/OAuth2OOo.oxt) which I have just pushed and which fixes this problem.

Please confirm so that I can close this issue.

**Comment by Spokey42** [comment]
yes, I can connect now.

thank-you for the quick resonse.
