### ISSUE TITLE
L'extension est-elle compatible avec la dernière version (LibO 24.8) ?

### ISSUE THREAD

**Issue by presb** [prrvchr/OAuth2OOo#18]
Bonjour,
Je viens de mettre à jour libreoffice vers la version 24.8.0.3 et dans le gestionnaire des extensions, l'extension OAuth2OOo (version 1.3.7) est grisée avec un avertissement.
Voici l'avertissement que j'obtiens quand j'essaye de la réactiver :
![image](https://github.com/user-attachments/assets/233458ee-e429-44d5-a646-68c22360a3d2)
Merci d'avance pour votre aide.

**Comment by prrvchr** [comment]
Bonjour persb,

Je viens d'ajouter les binaires Python 3.9 pour Windows 32 et 64 bits afin de rendre accessible la nouvelle version **24.8.x** de LibreOffice. Il est nécessaire de re-télécharger la dernière version 1.3.7.

Toutes les autres extensions doivent avoir le même problème, je dois également les mettre à jour afin qu'elles fonctionnent sous LibreOffice **24.8.x**

**Comment by presb** [comment]
Bonjour,
En téléchargeant la nouvelle version, tout s'installe correctement.
Merci pour votre efficacité.
