### ISSUE TITLE
Google broke it!

### ISSUE THREAD

**Issue by memand** [prrvchr/OAuth2OOo#2]
Everything is working fine untill we have to auth, it redirect propperly to the default browser and then this happens (att.)
![2020-01-25-132142_720x287_scrot](https://user-images.githubusercontent.com/2955763/73120975-3e780d00-3f75-11ea-8115-21932cf9655b.png)

**Comment by prrvchr** [comment]
Hi memand,

Having reached the limit of the first 100 connections, OAuth2OOo is effectively now blocked .. thank you for warning me, I couldn't see it myself...

I had to finalize gDriveOOo as well as gContactOOo in order to send Google a video justifying scopes claimed by OAuth2OOo...

It's done and I'm waiting for their response, hoping it will be positive...

**Comment by prrvchr** [comment]
Copy of the email I just sent them:

> Hi,
>
> I think that your validation procedure by video is not adapted to our OAuth2OOo, gContactOOo and gDriveOOo software.
>
> - It is important to realize that the OAuth2OOo, gContactOOo and gDriveOOo extensions do not collect any data, and only allow access and retification of data belonging to the user.
> - And that the refusal to validate the OAuth2OOo application amounts to violating your own data protection policy.
>
> In the absence of a positive response within 3 days, I would be forced to oblige you to apply your data protection policy.

I hope they will fold

**Comment by prrvchr** [comment]
OAuth2OOo is now an authorized application for the following scopes:
- https://www.googleapis.com/auth/drive
- https://www.googleapis.com/auth/contacts

I can close this issue...

**Comment by memand** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Why with the contact scope?                                                                                                                                             Sent from my BlackBerry — the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: February 10, 2020 10:10To: OAuth2OOo@noreply.github.comReply to: reply@reply.github.comCc: noajohan@gmail.com; author@noreply.github.comSubject: Re: [prrvchr/OAuth2OOo] Google broke it! (#2)  OAuth2OOo is now an authorized application for the following scopes:
https://www.googleapis.com/auth/drivehttps://www.googleapis.com/auth/contacts
I can close this issue...

**Comment by prrvchr** [comment]
For gContactOOo which allows to have a read-only copy of your Google Contacts in LibreOffice / OpenOffice

**Comment by memand** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Ok, cool! Anyways, thanks for the fix!                                                                                                                                             Sent from my BlackBerry — the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: February 10, 2020 14:54To: OAuth2OOo@noreply.github.comReply to: reply@reply.github.comCc: noajohan@gmail.com; author@noreply.github.comSubject: Re: [prrvchr/OAuth2OOo] Google broke it! (#2)  For gContactOOo which allows to have a read-only copy of your Google Contacts in LibreOffice / OpenOffice

**Comment by prrvchr** [comment]
You're welcome, thank you for alerting me.
