### ISSUE TITLE
Autorisation administrateur dans Google Workspace

### ISSUE THREAD

**Issue by presb** [prrvchr/OAuth2OOo#20]
Bonjour,
En essayant d'utiliser une nouvelle adresse google workspace, j'obtiens ce message d'erreur.
![image](https://github.com/user-attachments/assets/7419ad48-f2d6-424c-a6ca-c43f75cf1d3b)

Quelle application google faut-il activer dans la console d'administration ?
Merci.

**Comment by prrvchr** [comment]
Bonjour,

Je ne connais pas Google Workspace mais peut-être faut-il le configurer pour permettre l'utilisation de l'extension OAuth2OOo?

**Comment by presb** [comment]
J'ai trouvé. 
D'abord, dans la fenêtre vous informant du blocage, il y a la possibilité de demander l'accès. Il faut cliquer sur le lien.

Puis dans la console d'administration Google Workspace, il faut aller dans "Contrôle de l'accès des applications". Là, vous retrouvez la demande faite auparavant, et il suffit d'utiliser le lien proposé pour autoriser OAuthOOo à avoir accès aux ressources voulues. Vous pouvez autoriser un accès intégral, ou le paramétrer plus finement (ce que je n'ai pas fait...)
