### ISSUE TITLE
not authrization

### ISSUE THREAD

**Issue by drsnn** [prrvchr/OAuth2OOo#3]
hi,

 I tried to install google drive connection like below but  i can not do authorization request, while i enter my google email, it freeze and not authorize. I use mac pro.

```For LibreOffice V6.x and above:

In menu Tools - Options - LibreOffice - Advanced - Open Expert Configuration

Search for: UseSystemFileDialog (Found under: org.openoffice.Office.Common > Misc)

Edit or change “true” to “false” (set it to “false”)
Open your Google Drive:

In File - Open - File name enter: vnd.google-apps://your_account/ or vnd.google-apps:///

If you don’t give your_account, you will be asked for…

After authorizing the OAuthOOo application to access your Drive, your Google Drive should open!!! normally ;-)
```

[screenshot](https://imgur.com/DfhGV1m)

**Comment by prrvchr** [comment]
Hi drsnn,

So far, I have not been able to test on Mac so I am not sure of the result...

But hey it should work ...
After making sure you have installed OAuth2OOo beforehand, could you show me the logs available in Tools -> Options -> Internet -> OAuth2 Protocol - > View log

Thank you in advance

**Comment by prrvchr** [comment]
Hi drsnn,

A new [version 0.0.5](https://github.com/prrvchr/OAuth2OOo/raw/master/OAuth2OOo.oxt) is available. Now it works with LibreOffice 6.4.X and 7.X.

Can you make tests with this new version and open a new issue if necessary.
