### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by swissk** [prrvchr/OAuth2OOo#5]
Hi,

I followed your instructions and got the following message after the last step.

Sign in with Google temporarily disabled for this app

This app has not been verified yet by Google in order to use Google Sign In.

Any ideas what to do?

**Comment by prrvchr** [comment]
Hi,
Only scopes for gDriveOOO (url = vnd.google-apps) and gContactOOo (url = people.googleapis.com) are currently registered with Google.
Any other scope will give this type of error because it is not registered with Google ... [see last response of this issue](https://github.com/prrvchr/OAuth2OOo/issues/4)

**Comment by prrvchr** [comment]
Normally you must do in LibreOffice:
File -> Open (not Open Remote)
In File name field put: vnd.google-apps://your_account@gmail.com/
Click the Open button.
check the conditions of use of OAuth2OOo (without changing the configuration)
Sign in the Google sign in with your account...
And accept the conditions...

**Comment by prrvchr** [comment]
Please keep me informed, even if it works, that I can close the issue

**Comment by swissk** [comment]
Hi prrvchr,

I really cannot follow your instructions.

When I go File -> Open (not Open Remote) there is no File name field. I am
using LO 6.4.4.2. And when I use the OAuth2OOo wizard the google sign in
error shows up.

Regards,

Swissjs

prrvchr <notifications@github.com> schrieb am Do., 6. Aug. 2020, 15:51:

**Comment by prrvchr** [comment]
Hi  swissk ,

Did you configure LibreOffice so that it does not use the system file dialog because by default the system file dialog is used?

Follow the instructions: [Configure LibreOffice Open / Save dialogs](https://github.com/prrvchr/gDriveOOo#configure-libreoffice-open--save-dialogs)

Thank you for confirming

**Comment by swissk** [comment]
Hi prrvchr,

After configuring the dialog and rechecking gDriveOOo is installed. After adding vnd.google-apps://account_name and clicking OPEN I get NONEXISTENT OBJECT  NONEXISTENT FILE. 

Thank you for your help

**Comment by prrvchr** [comment]
> vnd.google-apps://account_name
is not the correct syntax, I don't know your account if there is no slash at the end

> vnd.google-apps://account_name**/**
is the correct syntax

**Comment by swissk** [comment]
Hi prrvchr,

that corrected the error. Now I get:
If you can see this, it means that the installation of the Yaws web server software on this system was successful. You may now add content to this directory and replace this page.
Seeing this instead of the website you expected?

Thank you

**Comment by prrvchr** [comment]
OAuth2OOo uses port 8080 to receive the response from Google after confirming acceptance.
Maybe another application (Yaws web server software) is already using this port?
Can you uninstall this application?

**Comment by swissk** [comment]
Hi prrvchr,

I works now. I will try it and comment in case of any problem.

Regards

**Comment by prrvchr** [comment]
This is good news.
If there are any malfunctions, do not hesitate to open a new issue if necessary.
It allows me to improve the quality ...
Thanks again, you are welcome...
