### ISSUE TITLE
6 digit authorization code

### ISSUE THREAD

**Issue by swissk** [prrvchr/OAuth2OOo#6]
Hi prrvchr,

While testing and trying to save to google drive a dialog requests 6 digit pin number. Two step authentication is disabled in Google.

Regards

**Comment by prrvchr** [comment]
Hi  swissk,

First, thank you to report any malfunctions, this allows me to improve the quality of the software...

Could you tell me more about the procedure to follow to arrive at this error message, as:
I'm creating a new file, then looking to save it with File -> Save As ...
This allows me to put myself in the same conditions and get the same error message...

**Comment by swissk** [comment]
Hi prrvchr,

I created a file and want to save it to Google Drive. I use SAVE AS and I cannot see the drive, so I change to SAVE REMOTE and a dialog pops-up and asks for MASTER PASSWORD, I enter the password and another dialog pops-up asking for a 6 digit pin.

**Comment by prrvchr** [comment]
Hi  swissk,

`I use File -> SAVE AS and I cannot see the drive`
If you don't see your Google Drive, just put:
**vnd.googlr_apps://your_account/**
After you can browse your Drive and give a new file name.
Never use File - > Save Remote, this can't work... (because your are using the LibreOffice Api)

**Comment by swissk** [comment]
Hi prrvchr,

Did that same result.

**Comment by prrvchr** [comment]
Hi [swissk](https://github.com/swissk),

First of all thank you for taking the time to create an issue, this allows me to improve the quality of the extensions.

The extensions have changed a lot since this issue was opened. I allow myself to close it and ask you to reopen one if necessary.
