### ISSUE TITLE
How to make Mail Merge use the token?

### ISSUE THREAD

**Issue by stragu** [prrvchr/OAuth2OOo#7]
Hi there!

I am not sure if it is my lack of understanding or a lack of documentation, but: once the OAuth2 has been successfully established, how does one make Mail Merge in LibreOffice use that authentication to send emails with that email account?

I am using the following at the moment:

Version: 7.2.1.1 (x64) / LibreOffice Community
Build ID: 3cfc32d9754d2d239bd8ce2941029c12873010c1
CPU threads: 8; OS: Windows 10.0 Build 19043; UI render: default; VCL: win
Locale: en-AU (en_AU); UI: en-US
Calc: threaded

with OAuth2OOo version 0.0.5

**Comment by prrvchr** [comment]
Hi [stragu](https://github.com/stragu),

First of all thank you for taking the time to create an issue, this allows me to improve the quality of the extensions.

To make mail merge, you need to follow the [**smtpMailerOOo documentation**](https://prrvchr.github.io/smtpMailerOOo/). Do not use OAuth2OOo directly, it will be launched automatically by smtpMailerOOo...

As I think I have solved this problem, certainly with a lot of delay :-) , I allow myself to close this issue
