### ISSUE TITLE
only able to "add" URL after choosing a provider and a scope

### ISSUE THREAD

**Issue by stragu** [prrvchr/OAuth2OOo#8]
This is a minor inconvenience, but I thought I'd report it:

If pasting a URL into the "URL" field in the OAuth2 settings, the "Add" button is greyed out.
One has to first fill in the "Provider" and "Scopes" fields, before being able to click "Add". And once you click "Add", it empties the "Provider" and "Scopes" fields, so you have to fill them in once again before being able to click "Next".

This is on:

* Windows 10
* LibreOffice 7.2.1.1

**Comment by prrvchr** [comment]
Hi [stragu](https://github.com/stragu),

First of all thank you for taking the time to create an issue, this allows me to improve the quality of the extensions.

The wizard used by OAuth2OOo is the first one I wrote... and unfortunately as it does not follow the Model-View-Controller Pattern., it is very difficult to maintain.

In fact, these problems can only be solved by a complete rewrite of the wizard following the MVC model.

It will be done soon, but I allow myself to close this issue although the problem persists...
